---
apiVersion: v1
kind: Service
metadata:
  name: movieservice
  labels:
    app: movieservice
spec:
  type: NodePort
  selector:
    app: movieservice
  ports:
    - protocol: TCP
      port: 8080
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: movieservice
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: movieservice
    spec:
      containers:
        - name: movieservice
          image: veact/movieservice:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2